spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/thingspire?serverTimezone=UTC&characterEncoding=UTF-8?allowPublicKeyRetrieval=true&useSSL=falses
    password: 200356family
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
mybatis:
  mapper-locations: classpath*:repository/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
